export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#FFFFFF',
  SECOND_BACKGROUND_COLOR: '#0090E2',
  PRIMARY_COLOR: '#38C7B4',
  SECONDARY_COLOR: '#006ABF',
  SECONDARY_TEXT_COLOR: '#708FA9',
  PRIMARY_TEXT_COLOR: '#2D3D4A',
  PRIMARY_LIGHT_TEXT_COLOR: '#7C7C7C',
  TEXT_PLACEHOLDER_COLOR: '#7C7C7C',
  PRIMARY_BUTTON_COLOR: '#0090E2',
  INPUT_BACKGROUND_COLOR: '#F7F7F7',
  WHITE_COLOR: '#FFF',
  SMALL_BODY_TEXT_COLOR:'#4C4F4D',


  PRIMARY_LIGHT_COLOR: '#C02DBF',
  PRIMARY_INACTIVE_COLOR: '#32b1e940',
  BACKGROUND_COLOR: '#FFFFFF',
  INPUT_BORDER_COLOR: '#8F92A1',
  PRIMARY_BUTTON_COLOR_ACTIVE: '#101D70',
  SECONDARY_BUTTON_COLOR: '#FFFFFF',
  OFF_WHITE_COLOR: '#EFF0EE',
  SUCCESS_COLOR: '#56C597',
  FAILED_COLOR: 'red',
  INPUT_COLOR: '#8d87ba',
  HELPER_TEXT_COLOR: '#7862FF',
  BLACK_TEXT_COLOR: '#000',
 
  SUB_TEXT_COLOR: '#8F9BB3',


  RED:'red',
  EDIT_RED:'#F31E64',
  YELLOW:'#EFCE4A',
  GREEN:'#17D142'
};
//#DAD5FA